[mypy]
python_version = 3.10
ignore_missing_imports = True
follow_imports = skip
allow_untyped_defs = True
allow_untyped_calls = True
warn_unused_ignores = False
exclude = (
    ^tests/load/|
    ^api/docs/|
    ^app/|
    ^android/|
    ^ios/
)
